spring:
  application:
    name: eureka_server
  profiles:
    active: localhost

---
spring:
  profiles: localhost

info:
  componenet: Eureka Server - Github - Localhost

eureka:
  instance:
    appname: eureka_server
    hostname: eureka_server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka

server:
  port: 8761
---
spring:
  profiles: stage

info:
  componenet: Eureka Server - Github - Stage

eureka:
  instance:
    appname: eureka_server
    hostname: eureka_server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka

server:
  port: 8765
